// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GLSL/450/modules/Includes.hpp>

std::string IncludesAmountLightsModuleCode =
"\
#ifndef HOPE__SHADER_AMOUNT_LIGHTS\n\
#define HOPE__SHADER_AMOUNT_LIGHTS\n\
\n\
#define MAX_DIRECTIONAL_LIGHTS  1\n\
#define MAX_POINT_LIGHTS        32\n\
#define MAX_SPOT_LIGHTS         8\n\
\n\
#endif\n\
" ;

std::string IncludesTextureUnitsModuleCode =
"\
#ifndef HOPE__TEXTURE_UNIT_BINDINGS\n\
#define HOPE__TEXTURE_UNIT_BINDINGS\n\
\n\
#define SHADOW_DEPTH_MAP_BINDING_UNIT 9\n\
\n\
#endif\n\
" ;

std::string IncludesBlockBindingsModuleCode =
"\
#ifndef HOPE__SHADER_BLOCK_BINDINGS\n\
#define HOPE__SHADER_BLOCK_BINDINGS\n\
\n\
#define BASE_DATA_UBO_BINDING_INDEX 0\n\
#define MODEL_DATA_UBO_BINDING_INDEX 1\n\
#define LIGHTS_DATA_UBO_BINDING_INDEX 2\n\
\n\
#endif\n\
" ;

