// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__BLINNPHONG_MATERIAL_SHADER_SRC__
#define __HOPE__BLINNPHONG_MATERIAL_SHADER_SRC__

#include <string>

extern std::string BlinnPhongForwardFragmentCode ;
extern std::string BlinnPhongDeferredFragmentCode ;
extern std::string BlinnPhongForwardVertexCode ;
extern std::string BlinnPhongDeferredVertexCode ;

#endif
