// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__BASE_DATA_BLOCK_MATERIAL_SHADER_SRC__
#define __HOPE__BASE_DATA_BLOCK_MATERIAL_SHADER_SRC__

#include <string>

extern std::string BaseDataBlockVertexCode ;

#endif
