// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__AORENDERING_MATERIAL_SHADER_SRC__
#define __HOPE__AORENDERING_MATERIAL_SHADER_SRC__

#include <string>

extern std::string AoRenderingSsaoFragmentCode ;
extern std::string AoRenderingSsaoVertexCode ;
extern std::string AoRenderingBlurFragmentCode ;

#endif
