// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__SHADOWS_MATERIAL_SHADER_SRC__
#define __HOPE__SHADOWS_MATERIAL_SHADER_SRC__

#include <string>

extern std::string ShadowsShadowCalculationModuleCode ;
extern std::string ShadowsDirLightShadowsVertexCode ;
extern std::string ShadowsDirLightShadowsFragmentCode ;

#endif
