// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GL/4.5/FunctionsUtility.hpp>

std::string FunctionsUtilityFragmentCode =
"\
vec3 AdjustNormalVector(mat3 tbnMatrix, vec3 normalValue) {\n\
    vec3 adjustedNormalVector = normalize((normalValue * 2.f) - 1.f) ;\n\
    adjustedNormalVector = normalize(tbnMatrix * adjustedNormalVector) ;\n\
    return adjustedNormalVector ;\n\
}\n\
" ;

