version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.2-stretch-browsers
        steps:
            - checkout
            # Dependencies for HOPEful (3D engine library)
            - run: sudo apt-get update; sudo apt-get install freeglut3 freeglut3-dev xorg-dev libglu1-mesa-dev
            # Get the source code from GLFW 3.2.1, compile it and install it.
            - run: wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip
            - run: unzip glfw-3.2.1.zip
            - run: cd glfw-3.2.1 && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON .. && make && sudo make install
            # Get the source code from GLEW 2.0.0, compile it and install it.
            - run: wget https://github.com/nigels-com/glew/releases/download/glew-2.0.0/glew-2.0.0.tgz
            - run: tar zxfv glew-2.0.0.tgz
            - run: cd glew-2.0.0/build/ && cmake ./cmake && make && sudo make install
            # Get the source code from ASSIMP 4.1.0, compile it and install it.
            - run: wget https://github.com/assimp/assimp/archive/v4.1.0.tar.gz
            - run: tar zxfv v4.1.0.tar.gz
            - run: cd assimp-4.1.0 && cmake . && make && sudo make install

            # Build libraries
            - run: cd Libraries && cmake . && make
            # Build functional tests and run it
            ## DOOM
            - run: cd Softwares/Tests/DOOMful && cmake . && make
            - run: cd Softwares/Tests/DOOMful/Chrono/bin && ./TestChrono.exe
            - run: cd Softwares/Tests/DOOMful/LogSystem/bin && ./TestLogSystem.exe
            - run: cd Softwares/Tests/DOOMful/Profiler/bin && ./TestProfiler.exe
            - run: cd Softwares/Tests/DOOMful/Random/bin && ./TestRandom.exe
            ## MIND
            - run: cd Softwares/Tests/MINDful && cmake -DWITH_EMULATED_SIMD=OFF . && make
            - run: cd Softwares/Tests/MINDful/Performances/bin && ./Performances.exe
            - run: cd Softwares/Tests/MINDful && cmake -DWITH_EMULATED_SIMD=ON . && make
            - run: cd Softwares/Tests/MINDful/Performances/bin && ./Performances.exe
            # Build unit tests and run it (using CPU SIMD if available)
            - run: cd UnitTests && cmake -DWITH_EMULATED_SIMD=OFF . && make
            - run: cd UnitTests/DOOMful/bin && ./DOOMUnitTest.exe
            - run: cd UnitTests/MINDful/bin && ./MINDUnitTest.exe
            - run: cd UnitTests/HOPEful/bin && ./HOPEUnitTest.exe
            - run: cd UnitTests && make clean
            # Build unit tests and run it (using emulated SIMD)
            - run: cd UnitTests && cmake -DWITH_EMULATED_SIMD=ON . && make
            - run: cd UnitTests/DOOMful/bin && ./DOOMUnitTest.exe
            - run: cd UnitTests/MINDful/bin && ./MINDUnitTest.exe
            - run: cd UnitTests/HOPEful/bin && ./HOPEUnitTest.exe
            - run: cd UnitTests && make clean
