version: 2
jobs:
    build:
        docker:
            - image: dcarlus/harmful0.0.3
        steps:
            - checkout

            # Build libraries
            - run: cd Libraries && ./build
            # Build functional tests and run it
            ## DOOM
            - run: cd Softwares/Tests/DOOMful && cmake . && make
            - run: cd Softwares/Tests/DOOMful/Chrono/bin && ./TestChrono.exe
            - run: cd Softwares/Tests/DOOMful/LogSystem/bin && ./TestLogSystem.exe
            - run: cd Softwares/Tests/DOOMful/Profiler/bin && ./TestProfiler.exe
            - run: cd Softwares/Tests/DOOMful/Random/bin && ./TestRandom.exe
            ## MIND
            - run: cd Softwares/Tests/MINDful && cmake . && make
            - run: cd Softwares/Tests/MINDful/Performances/bin && ./Performances.exe
            # Build unit tests and run it (using CPU SIMD if available)
            - run: cd UnitTests && cmake . && make
            - run: cd UnitTests/DOOMful/bin && ./DOOMUnitTest.exe
            - run: cd UnitTests/MINDful/bin && ./MINDUnitTest.exe
            - run: cd UnitTests/HOPEful/bin && ./HOPEUnitTest.exe
            - run: cd UnitTests && make clean
