#ifndef HOPE__AO_BINDINGS
#define HOPE__AO_BINDINGS

#define UNIFORM_AO_USE_LOCATION 30
#define UNIFORM_AO_KERNEL_LOCATION UNIFORM_AO_USE_LOCATION + 1
#define AO_MAP_BINDING_UNIT   4

#define AO_KERNEL_SIZE  64
#define AO_RADIUS       0.5
#define AO_BIAS         0.25

#endif
