// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__DEFERREDPASSES_MATERIAL_SHADER_SRC__
#define __HOPE__DEFERREDPASSES_MATERIAL_SHADER_SRC__

#include <string>

extern std::string DeferredPassesSpecularFragmentCode ;
extern std::string DeferredPassesPositionVertexCode ;
extern std::string DeferredPassesNormalFragmentCode ;
extern std::string DeferredPassesTexCoordVertexCode ;
extern std::string DeferredPassesAlbedoFragmentCode ;
extern std::string DeferredPassesNormalMapFragmentCode ;
extern std::string DeferredPassesNormalVertexCode ;
extern std::string DeferredPassesNormalMapVertexCode ;
extern std::string DeferredPassesSpecularMapFragmentCode ;
extern std::string DeferredPassesPositionFragmentCode ;
extern std::string DeferredPassesAlbedoMapFragmentCode ;

#endif
