// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__MODULES_MATERIAL_SHADER_SRC__
#define __HOPE__MODULES_MATERIAL_SHADER_SRC__

#include <string>

extern std::string ModulesDirectiveModuleCode ;
extern std::string ModulesBaseDataBlockModuleCode ;
extern std::string ModulesModelDataBlockModuleCode ;

#endif
