#ifndef __GLSL2CPP__STRINGS__
#define __GLSL2CPP__STRINGS__

#define WarningAutomaticGeneration      "// WARNING: This file is automatically generated. Any manual modification will be removed."

#define VertexShaderVarSuffix           "VertexCode"
#define FragmentShaderVarSuffix         "FragmentCode"
#define GeometryShaderVarSuffix         "GeometryCode"
#define GLSLModuleVarSuffix             "ModuleCode"

#endif
