// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GL/4.5/modules/AmountLights.hpp>

std::string AmountLightsFragmentCode =
"\
// WARNING: This file is automatically generated. Any manual modification will be removed.\n\
#define MAX_DIRECTIONAL_LIGHTS  4\n\
#define MAX_POINT_LIGHTS        32\n\
#define MAX_SPOT_LIGHTS         8\n\
" ;

