// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GL/4.5/modules/BlockBindings.hpp>

std::string BlockBindingsFragmentCode =
"\
// WARNING: This file is automatically generated. Any manual modification will be removed.\n\
#ifndef HOPE__SHADER_BLOCK_BINDINGS\n\
#define HOPE__SHADER_BLOCK_BINDINGS\n\
\n\
#define BASE_DATA_UBO_BINDING_INDEX 0\n\
#define MODEL_DATA_UBO_BINDING_INDEX 1\n\
#define LIGHTS_DATA_UBO_BINDING_INDEX 2\n\
\n\
#endif\n\
" ;

