// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GL/4.5/modules/Directive.hpp>

std::string DirectiveFragmentCode =
"\
#version 450 core    // OpenGL 4.5\n\
" ;

