// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GL/4.5/modules/LightsDataBlock.hpp>

std::string LightsDataBlockFragmentCode =
"\
struct DirectionalLight {\n\
    // Direction of the light.\n\
    vec3 direction ;\n\
\n\
    // Color of the light.\n\
    vec3 color ;\n\
\n\
    // Power of the light.\n\
    float power ;\n\
\n\
    // Does the light produce a specular?\n\
    float generateSpecular ;\n\
} ;\n\
\n\
struct PointLight {\n\
    // Position of the light in the 3D space.\n\
    vec3 position ;\n\
\n\
    // Color of the light.\n\
    vec3 color ;\n\
\n\
    // Distance of the light effect.\n\
    float falloffDistance ;\n\
\n\
    // Linear attenuation of the light.\n\
    float linearAttenuation ;\n\
\n\
    // Quadratic attenuation of the light.\n\
    float quadraticAttenuation ;\n\
\n\
    // Power of the light.\n\
    float power ;\n\
\n\
    // Does the light produce a specular?\n\
    float generateSpecular ;\n\
} ;\n\
\n\
layout (std140, binding = LIGHTS_DATA_UBO_BINDING_INDEX) uniform LightsData\n\
{\n\
    DirectionalLight dirLights[MAX_DIRECTIONAL_LIGHTS] ;\n\
    PointLight pointLights[MAX_POINT_LIGHTS] ;\n\
    int amountDirectionalLights ;\n\
    int amountPointLights ;\n\
} ;\n\
" ;

