// WARNING: This file is automatically generated. Any manual modification will be removed.
#include <scene/components/materials/shaders/GL/4.5/modules/ModelDataBlock.hpp>

std::string ModelDataBlockVertexCode =
"\
layout (std140) uniform ModelData\n\
{\n\
    mat4 modelMatrix ;\n\
    mat4 modelViewMatrix ;\n\
    mat4 mvpMatrix ;\n\
    mat4 inverseModelMatrix ;\n\
    mat4 inverseModelViewMatrix ;\n\
    mat4 inverseMVPMatrix ;\n\
    mat4 normalMatrix ;\n\
    mat4 modelNormalMatrix ;\n\
    mat4 modelViewNormalMatrix ;\n\
} ;\n\
" ;

