// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__BLINNPHONG_MATERIAL_SHADER_SRC__
#define __HOPE__BLINNPHONG_MATERIAL_SHADER_SRC__

#include <string>

extern std::string BlinnPhongDeferredSpecularFragmentCode ;
extern std::string BlinnPhongForwardFragmentCode ;
extern std::string BlinnPhongDeferredVertexNormalVertexCode ;
extern std::string BlinnPhongDeferredNormalFragmentCode ;
extern std::string BlinnPhongDeferredPositionFragmentCode ;
extern std::string BlinnPhongForwardVertexCode ;
extern std::string BlinnPhongDeferredAlbedoFragmentCode ;
extern std::string BlinnPhongDeferredVertexPositionVertexCode ;

#endif
