// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__CUBEMAP_MATERIAL_SHADER_SRC__
#define __HOPE__CUBEMAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string CubemapDeferredVertexCode ;
extern std::string CubemapDeferredFragmentCode ;
extern std::string CubemapForwardVertexCode ;
extern std::string CubemapForwardFragmentCode ;

#endif
