// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__DIFFUSENORMALSPECULARMAP_MATERIAL_SHADER_SRC__
#define __HOPE__DIFFUSENORMALSPECULARMAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string DiffuseNormalSpecularMapForwardFragmentCode ;
extern std::string DiffuseNormalSpecularMapForwardVertexCode ;

#endif
