// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__DIFFUSENORMALMAP_MATERIAL_SHADER_SRC__
#define __HOPE__DIFFUSENORMALMAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string DiffuseNormalMapDeferredVertexCode ;
extern std::string DiffuseNormalMapDeferredFragmentCode ;
extern std::string DiffuseNormalMapForwardVertexCode ;
extern std::string DiffuseNormalMapForwardFragmentCode ;

#endif
