// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__INCLUDES_MATERIAL_SHADER_SRC__
#define __HOPE__INCLUDES_MATERIAL_SHADER_SRC__

#include <string>

extern std::string IncludesAmountLightsModuleCode ;
extern std::string IncludesTextureUnitsModuleCode ;
extern std::string IncludesBlockBindingsModuleCode ;

#endif
