FROM debian:sid
MAINTAINER Denis CARLUS < denis.carlus [at] hotmail.fr >

RUN apt-get update \
&& apt-get install -y git build-essential cmake \
freeglut3 freeglut3-dev xorg-dev libglu1-mesa-dev \
libglfw3-dev libglew-dev libassimp-dev libjpeg62-turbo-dev libpng-dev
