// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__DIFFUSE_MAP_MATERIAL_SHADER_SRC__
#define __HOPE__DIFFUSE_MAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string DiffuseMapVertexCode ;
extern std::string DiffuseMapFragmentCode ;

#endif
