// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__FUNCTIONS_UTILITY_MATERIAL_SHADER_SRC__
#define __HOPE__FUNCTIONS_UTILITY_MATERIAL_SHADER_SRC__

#include <string>

extern std::string FunctionsUtilityFragmentCode ;

#endif
