// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__MATERIAL_CUBEMAP_MATERIAL_SHADER_SRC__
#define __HOPE__MATERIAL_CUBEMAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string MaterialCubemapVertexCode ;
extern std::string MaterialCubemapFragmentCode ;

#endif
