// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__MATERIAL_DIFFUSE_MAP_MATERIAL_SHADER_SRC__
#define __HOPE__MATERIAL_DIFFUSE_MAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string MaterialDiffuseMapVertexCode ;
extern std::string MaterialDiffuseMapFragmentCode ;

#endif
