// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__MATERIAL_DIFFUSE_NORMAL_SPECULAR_MAP_MATERIAL_SHADER_SRC__
#define __HOPE__MATERIAL_DIFFUSE_NORMAL_SPECULAR_MAP_MATERIAL_SHADER_SRC__

#include <string>

extern std::string MaterialDiffuseNormalSpecularMapVertexCode ;
extern std::string MaterialDiffuseNormalSpecularMapFragmentCode ;

#endif
