// WARNING: This file is automatically generated. Any manual modification will be removed.
#ifndef __HOPE__PHONG_MATERIAL_SHADER_SRC__
#define __HOPE__PHONG_MATERIAL_SHADER_SRC__

#include <string>

extern std::string PhongVertexCode ;
extern std::string PhongFragmentCode ;

#endif
